Update SVG package to fix
OfficeDev/Open-XML-SDK pull request #1222
Opened 2022-10-31 15:49 UTC by mikeebowen

Update SVG package to fix [CVE-2021-26701](https://github.com/advisories/GHSA-ghhp-997w-qr28)

2022-10-31 18:14 UTC, twsouthwick commented
@mikeebowen Update https://github.com/OfficeDev/Open-XML-SDK/blob/main/Directory.Build.props to use net472 as the samples project for framework instead of net46. People are slowly dropping support for older TFMs

2022-11-08 00:03 UTC, twsouthwick requested changes

2022-11-08 00:03 UTC, twsouthwick commented on Directory.Build.props
> +        <ProductTargetFrameworks>netstandard1.3;netstandard2.0;net35;net40;net472</ProductTargetFrameworks>
we don't want to change these. Just change the SamplesFramework ones

2022-11-10 17:11 UTC, mikeebowen commented
@twsouthwick , Do you know why the OfficeDev.Open-XML-SDK check hasn't run yet?

2022-11-11 18:20 UTC, mikeebowen commented
/azp run

2022-11-11 18:57 UTC, mikeebowen commented
/azp run

2022-11-12 00:06 UTC, tomjebo commented
/azp run

2022-11-14 19:10 UTC, tomjebo approved these changes

2022-11-14 19:27 UTC, twsouthwick approved these changes
LGTM! Thanks for just keeping the tfm change to the samples

2022-11-14 19:41 UTC, merged