Add November 2022 Updates
OfficeDev/Open-XML-SDK pull request #1248
Opened 2022-11-30 23:58 UTC by mikeebowen

- Added DocumentFormat.OpenXml.Office.SpreadSheetML.Y2022.PivotRichData namespace
- Added DocumentFormat.OpenXml.Office.PowerPoint.Y2019.Main.Command namespace
- Added DocumentFormat.OpenXml.Office.PowerPoint.Y2022.Main.Command namespace
- Added Child RichDataPivotCacheGuid to DocumentFormat.OpenXml.Office2010.Excel.PivotCacheDefinition

2022-12-01 00:39 UTC, twsouthwick commented
@mikeebowen merge changes from main. Make sure to remove the files marked as not in sync:

```
generated/DocumentFormat.OpenXml.Features/Microsoft.Interop.JavaScript.JSImportGenerator/Microsoft.Interop.JavaScript.JSExportGenerator/JSExports.g.cs
```

and similar

2022-12-01 00:40 UTC, twsouthwick commented
You'll also want to rerun the build locally to get some updates to the changed generated files

2022-12-05 18:51 UTC, twsouthwick requested changes
Other than the CHANGELOG line we should remove, LGTM

2022-12-05 18:51 UTC, twsouthwick commented on CHANGELOG.md
> +- Fixed .NET Core Remote Code Execution Vulnerability (#1222)
This is not true - this was in a test dependency, not anything we shipped externally

2022-12-05 19:14 UTC, mikeebowen commented on CHANGELOG.md
> +- Fixed .NET Core Remote Code Execution Vulnerability (#1222)
removed

2022-12-05 19:15 UTC, twsouthwick approved these changes

2022-12-05 21:41 UTC, twsouthwick commented
@mikeebowen any thing preventing this from merging at this point?

2022-12-05 21:48 UTC, tomjebo commented
@twsouthwick it should be ok to merge. We discussed this morning and I was thinking we wanted review of the PR by external contributors but it's not necessary, they can review a draft release with all the changes for 2.19.

2022-12-06 03:15 UTC, twsouthwick commented
You'll want to merge from main and rebuild to get some updated changes to the part generation I've merged in

2022-12-06 23:29 UTC, merged