Fixed NullReferenceException in OpenXmlElement RawOuterXml field
OfficeDev/Open-XML-SDK pull request #818
Opened 2020-11-19 18:35 UTC by aidilumarov

The current version of your code:

It sets _rawOuterXml to string.Empty if value is null, but instead of leaving the setter immediately, it resets the field to null at the end of the setter

The changes I made should resolve the issue.

Thanks.

2020-11-20 18:44 UTC, twsouthwick commented
@aidilumarov Thanks for the catch! Can you add a regression test so that it will be caught in the future?

2020-11-30 16:40 UTC, twsouthwick commented
@aidilumarov I'd like to get a 2.12.0 release out this week. If you can get some tests in, we'll have this as part of that release.

Also, can you update the CHANGELOG.md to include this?

2020-12-19 07:42 UTC, aidilumarov commented
@twsouthwick Sorry for taking long. I was off for several weeks. I have made the changes you asked for. Kind regards.

2020-12-23 17:32 UTC, twsouthwick requested changes
Looks like the build is broken. We have warnings as errors on CI builds

2020-12-23 17:32 UTC, twsouthwick commented on CHANGELOG.md
> +- Added regression tests in `DocumentFormat.OpenXml.Tests.OpenXmlElementTest2` to check for the mentioned exceptions in the future (#818)
This line is unneeded. I try to keep the changelog focused on observable changes to the library

2020-12-23 17:32 UTC, twsouthwick commented on src/DocumentFormat.OpenXml/Properties/launchSettings.json
> +    "DocumentFormat.OpenXml": {
This file and the other one appear unrelated to the change. I believe this is for vs code. If so, happy to take it but would like the rest of the projects supported as well. Best in a separate pr though

2021-01-08 01:05 UTC, twsouthwick commented
I've taken the liberty of updating the branch so it can be merged

2021-01-08 02:07 UTC, twsouthwick approved these changes

2021-01-08 03:44 UTC, merged