OpenXmlElement.CreateXmlReader: Prevent XmlConvertingReaderFactory from using a disposed XmlReader
OfficeDev/Open-XML-SDK pull request #940
Opened 2021-05-26 21:42 UTC by sorensenmatias

OpenXmlElement.CreateXmlReader: Prevent XmlConvertingReaderFactory from using a disposed XmlReader

2021-06-08 22:02 UTC, twsouthwick requested changes
Can you include a regression test for this!

Thanks for the fix!

2021-06-08 22:02 UTC, twsouthwick commented on src/DocumentFormat.OpenXml/OpenXmlElement.cs
> +            var stringReader = new StringReader(outerXml);
Can you add a comment here why we don't want to have a using?

2021-06-08 22:03 UTC, twsouthwick commented
/azp run

2021-06-11 20:01 UTC, sorensenmatias commented
@twsouthwick I added a test that shows the problem I encountered, and confirms the fix.

2021-06-19 19:12 UTC, sorensenmatias commented
Is there anything else I can help with to get this merged?

2021-06-24 16:56 UTC, twsouthwick commented
/azp run

2021-06-24 16:58 UTC, twsouthwick submitted a review, later dismissed
LGTM!

2021-06-24 16:59 UTC, twsouthwick commented
@sorensenmatias I've been pretty busy and so the delay is on me here. Once the tests pass, this can be merged in. Thanks for the contribution!

2021-06-24 17:18 UTC, twsouthwick commented
/azp run

2021-06-24 17:19 UTC, twsouthwick submitted a review, later dismissed

2021-06-25 10:12 UTC, sorensenmatias commented
Thanks @twsouthwick. I am not sure I completely follow though, is there a problem with the tests currently?

2021-06-25 18:47 UTC, twsouthwick commented
Yeah - we have warnings as error on, and there's a style warning that's getting flagged

2021-06-25 18:49 UTC, twsouthwick commented
/azp run

2021-06-25 18:50 UTC, twsouthwick commented
I've pushed a fix for it (needed to add a copyright)

2021-06-25 21:05 UTC, sorensenmatias commented
Thanks. I fixed one more warning regarding UTF8 BOM.

2021-07-03 21:31 UTC, twsouthwick commented
/azp run

2021-07-04 14:44 UTC, twsouthwick approved these changes

2021-07-04 14:45 UTC, merged